vectara:
  corpus_id: 6
  customer_id: 2081868821
  reindex: true

crawling:
  crawler_type: website

website_crawler:
  urls: ["https://arabicpost.net/"]
  delay: 1
  pages_source: crawl
  url_regex: [".*https://arabicpost.net/.*"]
  extraction: playwright
  max_depth: 3