vectara:
  corpus_id: 6
  customer_id: 2081868821
  reindex: true

crawling:
  crawler_type: website

website_crawler:
  urls: ["https://www.hbs.edu"]
  url_regex: [".*hbs.edu.*"]
  delay: 1
  pages_source: sitemap
  extraction: playwright
